name: Build and Push to Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: 283582579564.dkr.ecr.ca-central-1.amazonaws.com

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::283582579564:role/ShareFilesSecurelyTerraformAdministratorRole
          role-session-name: ShareFilesSecurelyGitHubActions
          aws-region: "ca-central-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build container
        working-directory: ./app
        run: |
          docker build \
          --build-arg git_sha=$GITHUB_SHA \
          -t $REGISTRY/share-files-securely:$GITHUB_SHA \
          -t $REGISTRY/share-files-securely:latest .

      - name: Push containers to Amazon ECR
        working-directory: ./app
        run: |
          docker push $REGISTRY/share-files-securely:$GITHUB_SHA
          docker push $REGISTRY/share-files-securely:latest

      - name: Deploy lambda
        run: |
          aws lambda update-function-code \
            --function-name "share_files_securely" \
            --image-uri $REGISTRY/share-files-securely:latest > /dev/null 2>&1
